version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Mapping frontend to localhost:3000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Mapping backend to localhost:5000
    environment:
      - FLASK_ENV=development
    devices:
      - "/dev/video0:/dev/video0"
    cap_add:
      - SYS_ADMIN
    privileged: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
