version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
    devices:
      - "/dev/video0:/dev/video0"
    cap_add:
      - SYS_ADMIN
    privileged: true

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    devices:
      - "/dev/video0:/dev/video0"
    cap_add:
      - SYS_ADMIN
    privileged: true

networks:
  app-network:
    driver: bridge
